on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n manageenginesdp -g manageenginesdpbe5f-rg --location "Brazil South" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n manageenginesdp --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n manageenginesdp --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n manageenginesdp --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: manageenginesdp.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t manageenginesdp.azurecr.io/kubernetes:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push manageenginesdp.azurecr.io/kubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kubernetes_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetesb9d2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetesb9d2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetesb9d2
        container-registry-url: manageenginesdp.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kubernetesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernetesb9d2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          manageenginesdp.azurecr.io/kubernetes:${{ github.sha }}
        imagepullsecrets: |
          kubernetesdockerauth   
